name: CI -> Deploy to My website
on:
  push:
    branches: [ deploy ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload ANTH-POS via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.ANTHPOS_FTP_SERVER }}
          user: ${{ secrets.ANTHPOS_FTP_USERNAME }}
          password: ${{ secrets.ANTHPOS_FTP_PASSWORD }}
